CREATE TABLE data_rekap
(
    TEMA DESIGN	VARCHAR(512),
    JUMLAH_PESANAN	VARCHAR(512),
    PRODUK	VARCHAR(512),
    BAHAN	VARCHAR(512),
    JUMLAH_PRODUK	VARCHAR(512),
    DATELINE	VARCHAR(512),
    FINISHING	VARCHAR(512),
    STATUS	VARCHAR(512)
);

INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('6332_BANG RACHMAN DIKCAB (DONNY-DIAN)(TOMKET)', '159 ', 'JERSEY', 'MILANO', '159 ', '3/7/21', '3/6/21', 'Tepat Waktu');
INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('6333_PO LETDA GANI ARTA DADU 3121-2 (DANI)', '68 ', 'JERSEY', 'POLYMESS', '68 ', '13/3/2021', '3/12/21', 'Tepat Waktu');
INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('ENLISTED', '70 ', 'JERSEY', 'BILABONG', '70 ', '3/9/21', '14/3/2021', 'Terlambat');
INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('6345_PO BANG TIRTA (DONNY)(TOMKET)', '90 ', 'JAKET', 'LOTTO', '90 ', '3/12/21', '3/14/21', 'Terlambat');
INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('6342_PO BANG ANDRIS_MARINE2_OGI (TOMKET)', '8 ', 'JERSEY', 'LYCRA', '8 ', '3/3/21', '3/3/21', 'Tepat Waktu');
INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('SHARK TEAM', '70 ', 'JERSEY', 'MILANO', '70 ', '3/9/21', '3/5/21', 'Tepat Waktu');
INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('6350_PO BANG ANGGA_PASPAMPRESS 3(MADI)(TOMKET)', '9 ', 'JERSEY', 'POLYMESS', '9 ', '3/11/21', '3/8/21', 'Tepat Waktu');
INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('6351_PO BANG IKO(madi)(TOMKET)', '2', 'JERSEY', 'BILABONG', '2', '3/12/21', '3/13/21', 'Terlambat');
INSERT INTO tableName (TEMA DESIGN, JUMLAH_PESANAN, PRODUK, BAHAN, JUMLAH_PRODUK, DATELINE, FINISHING, STATUS) VALUES ('6352_PO BAPA AGAN_MUTIARA STREET STELL (SABLON)', '12', 'JERSEY', 'LYCRA', '12', '3/10/21', '3/11/21', 'Terlambat');
